---
name: Zwift visual test
'on':
  workflow_call:
    inputs:
      image:
        description: zwift image to test
        required: true
        type: string
      registry:
        description: container registry
        default: ghcr.io
        required: false
        type: string
      username:
        description: username for container registry
        required: true
        type: string
    secrets:
      token:
        description: access token for container registry
        required: true
jobs:
  test:
    name: Visual test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y imagemagick x11-xserver-utils x11-apps
    - name: Checkout
      uses: actions/checkout@v7
      with:
        sparse-checkout: |
          tests/zwift-visual-test/reference-screenshot.png
        sparse-checkout-cone-mode: false
    - name: Login to container registry
      uses: docker/login-action@v4
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}
    - name: Start Zwift and capture screenshot
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        xvfb-run --auto-servernum --server-args="-ac -screen 0 800x600x24" bash -ec "
            docker run \
                --rm \
                -d \
                --name zwift-visual-test \
                -e DISPLAY=\${DISPLAY} \
                -e XAUTHORITY=\${XAUTHORITY} \
                -e CONTAINER_TOOL=docker \
                -e ZWIFT_NO_GAMEMODE=1 \
                --device=/dev/dri \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                -v \${XAUTHORITY}:\${XAUTHORITY} \
                ${IMAGE}
            sleep 30
            import -window root zwift-screenshot.png
            docker kill zwift-visual-test
        "
    - name: Compare to reference screenshot
      run: |
        convert tests/zwift-visual-test/reference-screenshot.png -draw 'rectangle 175,430 625,455' reference-normalized.png
        convert zwift-screenshot.png -draw 'rectangle 175,430 625,455' screenshot-normalized.png
        if ! different_pixels="$(compare \
            -metric AE \
            reference-normalized.png \
            screenshot-normalized.png \
            screenshot-diff.png \
            2>&1 \
        )" || [[ ${different_pixels} != "0" ]]; then
            echo "::error::Zwift screenshot differs from reference image! (pixel difference = ${different_pixels})"
            exit 1
        fi
    - name: Upload screenshot
      uses: actions/upload-artifact@v7
      with:
        path: zwift-screenshot.png
        archive: false
