---
name: Deploy zwift image
'on':
  workflow_call:
    inputs:
      registry:
        description: container registry to deploy to
        required: true
        type: string
      username:
        description: username for container registry
        required: true
        type: string
      image:
        description: image to deploy
        required: true
        type: string
      repository:
        description: repository to deploy to
        required: true
        type: string
      tag:
        description: image tag
        required: true
        type: string
    secrets:
      token:
        description: access token for container registry
        required: true
jobs:
  deploy:
    name: Deploy to container registry
    runs-on: ubuntu-latest
    steps:
    - name: Login to container registry
      uses: docker/login-action@v4
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}
    - name: Deploy image
      id: deploy
      env:
        IMAGE: ${{ inputs.image }}
        REGISTRY: ${{ inputs.registry }}
        USERNAME: ${{ inputs.username }}
        REPO: ${{ inputs.repository }}
        TAG: ${{ inputs.tag }}
      run: |
        repository="$(basename "${REPO}")"
        deploy_target="${REGISTRY}/${USERNAME}/${repository}"
        docker pull "${IMAGE}"
        docker tag "${IMAGE}" "${deploy_target}:${TAG}"
        docker tag "${IMAGE}" "${deploy_target}:latest"
        docker push "${deploy_target}:${TAG}"
        docker push "${deploy_target}:latest"
        echo "Deployed Zwift image: ${deploy_target}:${TAG}" >> "${GITHUB_STEP_SUMMARY}"
