---
name: Prune old images
'on':
  schedule:
  - cron: 0 0 * * 0 # weekly on Sundays
  workflow_dispatch:
    inputs:
      dry-run:
        description: list which tags would be pruned
        required: true
        type: boolean
concurrency:
  group: prune
jobs:
  prune-dockerhub:
    name: docker.io
    if: github.repository == 'netbrain/zwift'
    uses: ./.github/workflows/call_prune_container_registry.yaml
    with:
      api-url: https://hub.docker.com/v2
      api-type: docker-v2
      repository: ${{ github.repository }}
      username: ${{ vars.DOCKERHUB_USERNAME }}
      dry-run: &dry_run ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run }}
      keep-latest: true
      max-age: 365
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
  prune-ghcr:
    name: ghcr.io
    uses: ./.github/workflows/call_prune_container_registry.yaml
    with:
      api-url: https://api.github.com
      api-type: github
      repository: ${{ github.repository }}
      username: ${{ github.actor }}
      dry-run: *dry_run
      keep-latest: true
      max-age: 30
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
