---
name: Build 🡺 Test 🡺 Deploy
'on':
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 1 */3 * # on the first at 00:00 every three months
  - cron: 0 * * * * # every hour
  workflow_dispatch:
    inputs:
      rebuild:
        description: rebuild the image even if not needed
        required: true
        type: boolean
jobs:
  build:
    name: Build
    concurrency:
      group: build
      queue: max
    uses: ./.github/workflows/call_build_image.yaml
    with:
      environment: staging
      environment-url: ${{ format('https://ghcr.io/{0}', github.repository) }}
      rebuild: true # TODO use condition on next line
      # rebuild: ${{ ( github.event_name == 'schedule' && github.event.schedule == '0 0 1 */3 *' ) || ( github.event_name ==
      #   'workflow_dispatch' && inputs.rebuild ) }}
      registry: ghcr.io
      repository: ${{ github.repository }}
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    if: github.event_name != 'schedule' || needs.build.outputs.updated == '1'
    needs: build
    uses: ./.github/workflows/call_test_image_visual.yaml
    with:
      image: ${{ needs.build.outputs.image }}
  deploy:
    name: Deploy
    if: needs.build.outputs.updated == '1' # TODO && github.event_name != 'pull_request'
    needs:
    - build
    - test
    concurrency:
      group: deploy
      cancel-in-progress: true
    uses: ./.github/workflows/call_deploy_image.yaml
    with:
      environment: production
      environment-url: ${{ format('https://hub.docker.com/r/{0}/tags', vars.DOCKERHUB_REPOSITORY) }}
      image: ${{ needs.build.outputs.image }}
      registry: docker.io
      username: ${{ vars.DOCKERHUB_USERNAME }}
      repository: ${{ vars.DOCKERHUB_REPOSITORY }}
      tag: ${{ needs.build.outputs.version }}
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
