---
name: Zwift tests
'on':
  workflow_dispatch:
  pull_request:
concurrency:
  group: zwift-container-image
jobs:
  build:
    name: Build container image
    uses: ./.github/workflows/zwift_build_if_needed.yaml
    with:
      repository: ${{ github.repository }}
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test container image
    needs: build
    uses: ./.github/workflows/zwift_visual_test.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
