---
name: Zwift visual test
'on':
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  zwift_visual_test:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y x11-xserver-utils x11-apps
    - uses: netbrain/free-disk-space-action@v0.0.1
    - name: Checkout
      uses: actions/checkout@v7
    - name: Start Zwift and capture screenshot
      run: |
        export DISPLAY=":99"
        Xvfb "${DISPLAY}" -ac -screen 0 "800x600x24" -nolisten tcp &
        sleep 3
        xhost +
        docker run \
            --rm \
            -d \
            --name zwift-visual-test \
            -e DISPLAY="${DISPLAY}" \
            -e CONTAINER_TOOL="docker" \
            -e ZWIFT_NO_GAMEMODE="1" \
            --device="/dev/dri:/dev/dri" \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            netbrain/zwift:latest
        sleep 30
        import -window root zwift-screenshot.png
        docker kill zwift-visual-test
    - name: Compare to reference screenshot
      run: |
        convert tests/zwift-visual-test/reference-screenshot.png -draw 'rectangle 175,430 625,455' zwift-screenshot-mask.png
        different_pixels="$(compare \
            -metric AE \
            -read-mask zwift-screenshot-mask.png \
            tests/zwift-visual-test/reference-screenshot.png \
            zwift-screenshot.png \
            zwift-screenshot-diff.png \
        )"
        if [[ ${different_pixels} != "0 (0)" ]]; then
            echo "::error::Zwift screenshot differs from reference image!"
            exit 1
        fi
    - name: Upload screenshot
      uses: actions/upload-artifact@v7
      with:
        path: zwift-screenshot.png
        archive: false
