---
name: Zwift updater
'on':
  workflow_dispatch:
  schedule:
  - cron: 0 * * * *
  push:
    branches:
    - master
concurrency:
  group: zwift-container-image
jobs:
  build:
    name: Build container image
    uses: ./.github/workflows/zwift_build_if_needed.yaml
    with:
      rebuild: false # TODO rebuild at midnight on the 1st of every three months: 0 0 1 */3 *
      repository: ${{ github.repository }}
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test container image
    needs: build
    uses: ./.github/workflows/zwift_visual_test.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      username: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy container image
    if: needs.build.outputs.updated == '1' && github.repository == 'netbrain/zwift'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
    - build
    - test
    steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Deploy image
      env:
        IMAGE: ${{ needs.build.outputs.image }}
        VERSION: ${{ needs.build.outputs.version }}
        REPO: ${{ github.repository }}
      run: |
        docker pull "${IMAGE}"
        docker tag "${IMAGE}" "${REPO@L}:${VERSION}"
        docker tag "${IMAGE}" "${REPO@L}:latest"
        docker push "${REPO@L}:${VERSION}"
        docker push "${REPO@L}:latest"
