---
name: Rebuild Zwift image
'on':
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 */3 *
  push:
    branches:
    - master
    - unstable
    paths:
    - src/Dockerfile
concurrency:
  group: zwift-container-image
jobs:
  zwift_rebuild_on_schedule:
    if: github.repository == 'netbrain/zwift' && github.event_name != 'push'
    strategy:
      fail-fast: false
      matrix:
        git_branch:
        - master
        - unstable
    uses: ./.github/workflows/zwift_build_from_scratch_impl.yaml
    with:
      git_branch: ${{ matrix.git_branch }}
      dockerhub_image: netbrain/zwift
    secrets:
      github_token: ${{ github.token }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  zwift_rebuild_on_push:
    if: github.repository == 'netbrain/zwift' && github.event_name == 'push'
    uses: ./.github/workflows/zwift_build_from_scratch_impl.yaml
    with:
      git_branch: ${{ github.ref_name }}
      dockerhub_image: netbrain/zwift
    secrets:
      github_token: ${{ github.token }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
