---
name: Update Zwift
'on':
  workflow_dispatch:
  schedule:
  - cron: 0 * * * *
concurrency:
  group: zwift-container-image
jobs:
  update_zwift:
    if: github.repository == 'netbrain/zwift'
    strategy:
      fail-fast: false
      matrix:
        git_branch:
        - master
        - unstable
    uses: ./.github/workflows/zwift_updater_impl.yaml
    with:
      git_branch: ${{ matrix.git_branch }}
      dockerhub_image: netbrain/zwift
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
